### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by carlolaitano** [liabru/jquery-match-height#56] opened 2015-03-09 15:24 UTC
I've got this working properly on desktop view, but the height of the elements will not reset responsively. It looks fine on desktop, but when i resize the viewport the height stays the same and doesn't reset to account for the new breakpoint, leaving a lot of extra space at the bottom.

**Comment by liabru** [comment] 2015-03-21 12:56
Would you be able to provide a jsfiddle that demonstrates the issue? Thanks

**Comment by petereberlecom** [comment] 2015-05-24 09:55
is it in the .resize() event? Because it works responsive with me?

**Comment by liabru** [comment] 2015-06-09 00:23
Is this still a problem? If so I will need a jsfiddle to reproduce it. Otherwise I will close the issue.

**Comment by WPThemer** [comment] 2015-10-03 01:18
I am having the same issue, it works fine if I manually drag and resize the browser, but if I click on resize icon of browser, it doesn't work... One reason could be one DIV has elements that respond to media queries and take like 1-2 seconds, and after that those get adjusted but this amazing plugin tried to immediately set the height which occurs before the media queries respond and adjust the layout... is there any way to fix this ? and secondly how can I change height to !important ?..

thanks for such an amaing plugin, been working on a theme since last year.. oh and I still have older version of this plugin.. jquery.matchHeight.js v0.5.2

regards

**Comment by liabru** [comment] 2015-10-04 12:12
@WPThemer have you tried with the latest version?

**Comment by WPThemer** [comment] 2015-10-05 02:05
Thanks Liabru, No - I have not tried the latest one, however I have changed he height to min-height and also on reszie I have used "bind" that fixed the problem for now...

thanks again...

**Comment by liabru** [comment] 2015-10-05 23:33
Fair enough, but I certainly recommend upgrading when you get the chance!

**Closed** 2015-11-11 21:26 UTC
